### ISSUE TITLE
Problemas encontrado e ajustes necessários

### ISSUE THREAD

**Issue by felipebs07** [hbrt-spx/Java-Init#1]
```
int N, i;
```
1. isso nao é uma boa pratica de código, por mais que fator do garbage no java que é muito bom é recomendavel evitar  esse tipo de declaração em estado inicial no codigo.
2. declare variaveis com nomes faceis de entender, desenvolvedor fora do projeto olhando esse codigo eu preciso entender toda a  estrutura para saber o que é N e I.

```
double[] notas = new double[N]
```
1.  nao fez tratativa para zero caso eu insera "zero provas" e nem para caso eu force um tipo inesperado no terminal que nao seja int.

```
 for (i = 0; i < N; i++) {
    System.out.print("Digite a " + (i+1) + "ª nota: ");
    notas[i] = sc.nextDouble();
```
1. Não faz sentido você deixar o valor subir para o sistema fazendo isso: notas[i] = sc.nextDouble() e validar depois se esta errado;

```
  if(notas[i] > 10){
      System.out.println("A nota deve ser de 0 a 10");
      i = -1;
  }
```

1. a validação diz que a nota deve ser entre 0 a 10, mas ela me permite colocar numeros negativos me retornando uma media negativa.
2. a parte   **i = -1;**, isso não é uma boa pratica, se meu usuario lançar 20 notas, e na nota 19 ela errar, isso esta gerando efeito coletaral de voltar para o meu loop lá no inicio, se caso criar um sistema que envia 1 milhao de notas, você vai me fazer volta para o inicio caso falte 1 registro de 1 milhão?

```
System.out.println(Arrays.stream(notas).sum()/N);
 if(Arrays.stream(notas).sum()/N >= 6){
```
1. se você chama isso duas vezes no codigo, você gera retrabalho para o sistema calcular toda vez , se eu tiver uma grande quantidade de notas você vai mandar esse calculo 2x, não faz sentido eu gerar essa carga de estresse sem motivo no código.

**Comment by hbrt-spx** [comment]
Corrigi quase todos os pontos, poderia revisar? @felipebs07

**Comment by felipebs07** [comment]
Boa, ficou só alguns aspectos que vamos trabalhar na mentoria
