### ISSUE TITLE
Correções

### ISSUE THREAD

**Issue by felipebs07** [hbrt-spx/Java-Init#2]
## Testes Unitários

1. Separar os testes por cenário: Quando a gente escreve testes, o ideal é testar uma coisa por vez. No seu código, você coloca vários cenários de teste no mesmo método calcularMedia(). O problema disso é que, se der erro, fica difícil saber qual cenário falhou. Por isso, é melhor criar um teste separado para cada situação. Por exemplo, um teste só para letras, outro para números negativos, e assim por diante.
2. Variáveis numero_1 e numero_2: Você criou essas variáveis (numero_1 e numero_2), mas não está usando elas. Aí, o que acontece? O código fica com "sujeira". Se essas variáveis não têm utilidade, o melhor é remover para deixar o código mais limpo.
3. Cenários que faltam testar: Você já validou alguns casos, como quando o usuário passa letras no lugar de números. Mas, faltam testar outros casos importantes, como:
             - Quando o valor é negativo (tipo -5)
            -  Quando o array de notas está vazio 
4. Nos seus testes, você está usando System.out.println() para mostrar as mensagens, certo? Mas, quando estamos fazendo testes unitários, o ideal é usar assertions. Elas ajudam a automatizar os testes. Com assertions, você pode dizer: "Eu espero que a média seja 8, então vou comparar isso com o que o código realmente calculou". Se a média não for 8, o JUnit avisa que o teste falhou. Na ultima mentoria te mandei um link sobre testes, utiliza ele para começamos a melhorar essa parte dos teste e você conseguir fazer algo solido.

## Java

Correções
1. Validar se o array está vazio no começo: Antes, você estava verificando se o array de notas estava vazio só depois de fazer um loop nas notas. Isso não é eficiente. Se as notas estão vazias, a gente já sabe que não tem nada para processar, então pode validar isso logo no início e evitar o trabalho desnecessário.
2. Usar um regex mais simples: O regex que você está usando valida números entre 0 e 10 e se não tem letras, mas se o sistema precisar de notas maiores no futuro, vai dar problema. O mais simples seria validar se a entrada é um número e, depois, fazer a verificação da faixa, para ver se não existe número negativo utilizando assim o regex, usando algo como: `^[0-9]+$`
3. Lançar exceções quando o dado estiver errado: Ao invés de só imprimir mensagens de erro (System.out.println()), é melhor lançar uma exceção. Assim, o programa sabe que algo deu errado e você pode capturar esse erro nos testes unitários. Isso deixa o código mais robusto e fácil de manter.
4. Tirar código desnecessário: No loop, você criou um contador para ver quantas notas válidas tinham. Mas, como você já sabe o tamanho do array de notas (notas.length), pode simplificar e evitar esse contador extra.

**Comment by hbrt-spx** [comment]
Bom dia Felipe, fiz algumas mudanças e estou com dificuldades no teste 'validadorDeNotas' no caso eu  entendo que o esperado seja um true ou uma exception, na parte de teste, independente de eu passar valores ou nao, ele ta caindo na exception.

**Comment by felipebs07** [comment]
## Java

No método `somaValores`, percebi que você usa double para a soma, mas no final retorna um valor convertido para int. Isso pode causar uma conversão inadequada, especialmente quando há valores decimais ou negativos. Se você está somando valores, deveria considerar números em todas as suas formas.

No método `validadorDeNotas`, a validação atual funciona apenas para números inteiros. No contexto de cálculo de média, você não está lidando com valores negativos. Seria interessante ajustar a regex para validar adequadamente os dois casos (somar e calcular média) separadamente, evitando limitar ambos ao mesmo tempo.

## Teste
O teste `void validadorDeNotas` não está adequado. Se você quer capturar uma exceção ao testar uma nota como "A", deve usar assertThrows, já que assertTrue sempre falhará enquanto a regex não aceitar letras.

É mais interessante validar o contexto completo, em vez de testar apenas calculadora.validadorDeNotas(...). Teste se o método calcularMedia ou calcularSoma executa o processo corretamente. Se, por exemplo, o método que calcula a média converte letras em números, o validadorDeNotas passaria, mas o cálculo estaria errado. Portanto, validar métodos isolados pode levar a resultados inconsistentes se o método principal falhar.

**Comment by felipebs07** [comment]
@hbrt-spx o projeto esta faltando o arquivo NumberValidateException na versão da main do seu projeto, acredito que não foi comitado, e não consigo testar corretamente.

![{1467CC72-D02E-4CCB-ABB6-7FDAE1E58623}](https://github.com/user-attachments/assets/3dab542c-e7a6-43e8-ba00-63caaa38d726)

**Comment by hbrt-spx** [comment]
Boa tarde Felipe, subi o arquivo, peço desculpas pelo transtorno.
